class NoFDError(RuntimeError): ...

class FileDescriptor:
    def close(self) -> None: ...
    def __enter__(self) -> FileDescriptor: ...
    def __exit__(self) -> None: ...
    def __del__(self) -> None: ...
