on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - "3.13"
          - "3.8"
    steps:
      - uses: actions/checkout@v5.0.0

      - uses: astral-sh/setup-uv@v6.7.0
        with:
          activate-environment: true
          python-version: "3.13"

      - name: install tox
        run: uv tool install --python-preference only-managed --python 3.13 tox --with tox-uv --with tox-gh

      - name: install python
        if: matrix.env != '3.13'
        run: uv python install --python-preference only-managed ${{ matrix.env }}

      - name: ruff (GA output format)
        run: uv run ruff check --output-format=github

      - name: Setup tox tests
        run: tox run -vv --notest --skip-missing-interpreters false
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.env }}
      
      - name: Run tests
        run: tox run --skip-pkg-install
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.env }}
